In [10]:
import h5py
import pyBigWig as pbw
import pandas as pd
import numpy as np

In [11]:
imr90_pred = h5py.File("/home/suncz/work/s02/Encode_epigenome/results/benchmark/EPCOT/dataset/succeed/4-cells/model/csv/logs/version_0/IMR-90.h5", "r")
imr90_pred.keys()

In [12]:
prediction = imr90_pred["prediction"]
prediction.shape

(19642, 896, 46)

In [21]:
prediction[0,:,10].shape

(896,)

In [ ]:
contig_df = pd.read_table("/home/suncz/work/s02/Encode_epigenome/results/preprocessed/1m-epcot/sequences.bed" , sep="\t",header= None)
contig_df.columns = ["chrom","start","end","name"]

In [28]:
signal_ls = []
num = 0
for seq,signal in zip(contig_df.values,prediction):
    chr = seq[0]
    start = int(seq[1])
    end = int(seq[2])
    signal = signal[:,4]
    num += 1
    for index,res_start in enumerate(range(start+1024*64,end-1024*64,1024)):
        res_end = res_start + 1024
        signal_ls.append([chr,res_start,res_end,signal[index]])
    print(num,end="\r")
tmp_df = pd.DataFrame(signal_ls,columns=["chr","start","end","signal"])
tmp_df.sort_values(by=["chr","start"],inplace=True)
tmp_df.drop_duplicates(subset=["chr","start","end"],inplace=True,keep="first")
tmp_df.to_csv(f"/home/suncz/work/s02/Encode_epigenome/results/benchmark/EPCOT/dataset/succeed/4-cells/model/csv/logs/version_0/imr90_ctcf_succeed_signal.bedGraph",sep="\t",index=False,header=False)

In [25]:
signal.shape

(896, 46)

In [17]:
tf_list = open("/home/suncz/work/s02/Encode_epigenome/results/benchmark/EPCOT/dataset/succeed/4-cells/tf.txt","r").readlines()
tf_list = [i.split()[0] for i in tf_list]

In [18]:
tf_list_dict = {}
for i,j in enumerate(tf_list):
    tf_list_dict[j] = i

In [19]:
tf_list_dict

{'ARID3A': 0,
 'ATF7': 1,
 'CEBPB': 2,
 'CREB1': 3,
 'CTCF': 4,
 'ELF1': 5,
 'EP300': 6,
 'FOXK2': 7,
 'GABPA': 8,
 'H2AFZ': 9,
 'H3K27ac': 10,
 'H3K27me3': 11,
 'H3K36me3': 12,
 'H3K4me1': 13,
 'H3K4me2': 14,
 'H3K4me3': 15,
 'H3K79me2': 16,
 'H3K9ac': 17,
 'H3K9me3': 18,
 'H4K20me1': 19,
 'HCFC1': 20,
 'HDAC2': 21,
 'JUND': 22,
 'MAFK': 23,
 'MAX': 24,
 'MAZ': 25,
 'MYC': 26,
 'NBN': 27,
 'NRF1': 28,
 'POLR2A': 29,
 'RAD21': 30,
 'RAD51': 31,
 'RCOR1': 32,
 'REST': 33,
 'RFX5': 34,
 'SIN3A': 35,
 'SP1': 36,
 'SRF': 37,
 'SUZ12': 38,
 'TAF1': 39,
 'TARDBP': 40,
 'TCF12': 41,
 'YBX1': 42,
 'ZBTB33': 43,
 'ZBTB40': 44,
 'ZNF24': 45}

In [29]:
df = pd.read_table('/home/suncz/work/s02/Encode_epigenome/results/target_human.txt', index_col=0,sep="\t")

In [30]:
df

,genome,identifier,file,clip,scale,sum_stat,experiment,factors,type,notes
index,,,,,,,,,,
0,1,ENCFF323ZYI,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K27ac,modification,esophagus muscularis mucosa
1,1,ENCFF631KUG,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ATAC-seq,NaN,NaN,DND-41
2,1,ENCFF539NFV,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,DNase-seq,NaN,NaN,head of caudate nucleus
3,1,ENCFF820NWA,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ATAC-seq,NaN,NaN,HG03135
4,1,ENCFF111KQE,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ATAC-seq,NaN,NaN,GM21390
...,...,...,...,...,...,...,...,...,...,...
6384,1,ENCFF801WCC,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K9me3,modification,thymus
6385,1,ENCFF103HHO,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K36me3,modification,muscle of trunk
6386,1,ENCFF934JEL,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K27me3,modification,muscle of trunk
6387,1,ENCFF922OMJ,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,DNase-seq,NaN,NaN,nephron progenitor cell
6388,1,ENCFF903ZCB,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,DNase-seq,NaN,NaN,H9

In [31]:
df_imr90 = df[df["notes"].isin(["IMR-90"])]

In [32]:
df_imr90

,genome,identifier,file,clip,scale,sum_stat,experiment,factors,type,notes
index,,,,,,,,,,
522,1,ENCFF439NSO,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,BHLHE40,tf,IMR-90
730,1,ENCFF097YGG,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,MXI1,tf,IMR-90
792,1,ENCFF297OSJ,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,RCOR1,tf,IMR-90
835,1,ENCFF124JSL,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,CHD1,tf,IMR-90
917,1,ENCFF775AQV,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,SMC3,tf,IMR-90
934,1,ENCFF079XTH,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,ELK1,tf,IMR-90
945,1,ENCFF662YFN,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,USF2,tf,IMR-90
967,1,ENCFF516QHD,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,FOS,tf,IMR-90
1183,1,ENCFF444OMD,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,POLR2A,tf,IMR-90
1303,1,ENCFF929VHJ,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,RAD21,tf,IMR-90
1448,1,ENCFF055ZCI,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,MAFK,tf,IMR-90
1462,1,ENCFF971HXR,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,DNase-seq,NaN,NaN,IMR-90
1704,1,ENCFF101PSS,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,CTCF,tf,IMR-90
2052,1,ENCFF290IBT,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,MAZ,tf,IMR-90
2068,1,ENCFF335ZXR,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,CEBPB,tf,IMR-90
2071,1,ENCFF039PUG,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,RFX5,tf,IMR-90
2146,1,ENCFF323RPM,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,DNase-seq,NaN,NaN,IMR-90
2170,1,ENCFF213VCW,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2BK12ac,modification,IMR-90
3171,1,ENCFF307NYW,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,NFE2L2,tf,IMR-90
3390,1,ENCFF513DXL,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2BK5ac,modification,IMR-90
3397,1,ENCFF524BQQ,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H4K5ac,modification,IMR-90
3415,1,ENCFF361LHT,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K14ac,modification,IMR-90
3444,1,ENCFF961CWW,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K79me2,modification,IMR-90
3445,1,ENCFF400CAD,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K4me2,modification,IMR-90
3514,1,ENCFF682HNO,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K9ac,modification,IMR-90
3974,1,ENCFF045HZZ,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K27me3,modification,IMR-90
3980,1,ENCFF443FLN,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2AK5ac,modification,IMR-90
4002,1,ENCFF217JTN,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2BK20ac,modification,IMR-90
4004,1,ENCFF222IQN,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K27ac,modification,IMR-90
4009,1,ENCFF335IHO,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H4K91ac,modification,IMR-90
4012,1,ENCFF398QPY,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H4K20me1,modification,IMR-90
4170,1,ENCFF148PNW,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K4me1,modification,IMR-90
4180,1,ENCFF614CMT,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H4K8ac,modification,IMR-90
4225,1,ENCFF314QXF,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K36me3,modification,IMR-90
4248,1,ENCFF984AUF,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2AFZ,modification,IMR-90
4249,1,ENCFF987LAC,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2AFZ,modification,IMR-90
4260,1,ENCFF049TRD,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K79me1,modification,IMR-90
4403,1,ENCFF752AQC,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2AK9ac,modification,IMR-90
4404,1,ENCFF625ZJC,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2AK9ac,modification,IMR-90
4456,1,ENCFF577LCU,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2BK120ac,modification,IMR-90
5231,1,ENCFF518GFI,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K4me3,modification,IMR-90
5232,1,ENCFF873YOP,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K23ac,modification,IMR-90
5234,1,ENCFF411RET,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K4ac,modification,IMR-90
5258,1,ENCFF242GOE,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H4K8ac,modification,IMR-90
5744,1,ENCFF733CJA,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K9me3,modification,IMR-90
5749,1,ENCFF363LML,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K79me1,modification,IMR-90
5767,1,ENCFF350ATK,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K56ac,modification,IMR-90
5776,1,ENCFF572ALP,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K18ac,modification,IMR-90
5792,1,ENCFF828SKT,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H2BK15ac,modification,IMR-90
5831,1,ENCFF164FXG,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ChIP-seq,H3K9me1,modification,IMR-90
5979,1,ENCFF770EAV,/home/suncz/work/s02/Encode_epigenome/data/ENC...,32,2,mean,ATAC-seq,NaN,NaN,IMR-90

In [38]:
56360613-1000*100,56360613+1000*100

(56260613, 56460613)

In [37]:
54300083 + 1000*200

54500083

In [16]:
df_imr90_select = df_imr90[df_imr90["factors"].isin(tf_list)]

In [67]:
test_npy = np.load('/home/suncz/work/s02/Encode_epigenome/results/preprocessed/1m-akita/seqs_cov/792.h5.npy', allow_pickle=True)

In [71]:
test_npy[:,64:-64].shape

(19642, 896)

In [96]:
df_imr90_select = df_imr90_select.drop_duplicates(subset=["factors"])

In [99]:
tf_name = []
corr_ls = []
for i in df_imr90_select.iloc:
    factors = i.factors
    name = i.name
    pred_index = tf_list_dict[factors]
    pred = prediction[:,:,pred_index]
    pred_chr10 = pred[contig_df[contig_df["chrom"] == "chr10"].index.values]
    target = np.load(f'/home/suncz/work/s02/Encode_epigenome/results/preprocessed/1m-akita/seqs_cov/{name}.h5.npy', allow_pickle=True)[:,64:-64]
    target_chr10 = target[contig_df[contig_df["chrom"] == "chr10"].index.values]
    corr = np.corrcoef(pred_chr10.flatten(), target_chr10.flatten())[0][1]
    pred_chr21 = pred[contig_df[contig_df["chrom"] == "chr21"].index.values]
    target_chr21 = target[contig_df[contig_df["chrom"] == "chr21"].index.values]
    corr_chr21 = np.corrcoef(pred_chr21.flatten(), target_chr21.flatten())[0][1]
    mean_corr = (corr + corr_chr21) / 2  # Calculating the average correlation
    tf_name.append(factors)
    corr_ls.append(mean_corr)
    print(factors, corr, corr_chr21, mean_corr)
succeed_imr90 = pd.DataFrame({"tf":tf_name, "corr":corr_ls})
succeed_imr90.to_csv('/home/suncz/work/s02/Encode_epigenome/results/benchmark/EPCOT/dataset/succeed/4-cells/model/csv/logs/version_0/imr90_corr.csv', index=False)

RCOR1 0.5813749187817024 0.5937580137426475 0.5875664662621749
POLR2A 0.7310266417607761 0.6226967515460162 0.6768616966533962
RAD21 0.8885999234939285 0.8788748841558054 0.8837374038248669
MAFK 0.2403572991807032 0.23127833267676812 0.23581781592873566
CTCF 0.9214128214944282 0.8914164181850585 0.9064146198397434
MAZ 0.8517375523796017 0.8241724861404146 0.8379550192600081
CEBPB 0.43022002873710996 0.47500204214754616 0.45261103544232806
RFX5 0.2741007750386846 0.2756518617234804 0.2748763183810825
H3K79me2 0.7309438518339016 0.7391249816246731 0.7350344167292874
H3K4me2 0.8101223166067864 0.8050549820907507 0.8075886493487685
H3K9ac 0.854326987204958 0.8475591346005568 0.8509430609027574
H3K27me3 0.6209098410991656 0.6110563932778907 0.6159831171885282
H3K27ac 0.7599993701579393 0.768150796987785 0.7640750835728621
H4K20me1 0.6355905700935706 0.7048057612474476 0.6701981656705092
H3K4me1 0.7501786749884025 0.7709531074565968 0.7605658912224997
H3K36me3 0.7293454138488548 0.7056215844480969 0.7174834991484758
H2AFZ 0.8220069625187704 0.728105524818948 0.7750562436688592
H3K4me3 0.8778029162195419 0.8810782330601021 0.879440574639822
H3K9me3 0.4943740452700345 0.45344520294834106 0.4739096241091878

### H1

In [ ]:
df_h1 = df[df["notes"].isin(["H1"])]
df_h1_select = df_h1[df_h1["factors"].isin(tf_list)]
df_h1_select = df_h1_select.drop_duplicates(subset=["factors"])

In [122]:
h1_pred = h5py.File("/home/suncz/work/s02/Encode_epigenome/results/benchmark/EPCOT/dataset/succeed/4-cells/model/csv/logs/version_0/H1.h5", "r")
prediction = h1_pred["prediction"]
prediction.shape

(19642, 896, 46)

In [123]:
tf_name = []
corr_ls = []
for i in df_h1_select.iloc:
    factors = i.factors
    name = i.name
    pred_index = tf_list_dict[factors]
    pred = prediction[:,:,pred_index]
    pred_chr10 = pred[contig_df[contig_df["chrom"] == "chr10"].index.values]
    target = np.load(f'/home/suncz/work/s02/Encode_epigenome/results/preprocessed/1m-akita/seqs_cov/{name}.h5.npy', allow_pickle=True)[:,64:-64]
    target_chr10 = target[contig_df[contig_df["chrom"] == "chr10"].index.values]
    corr = np.corrcoef(pred_chr10.flatten(), target_chr10.flatten())[0][1]
    pred_chr21 = pred[contig_df[contig_df["chrom"] == "chr21"].index.values]
    target_chr21 = target[contig_df[contig_df["chrom"] == "chr21"].index.values]
    corr_chr21 = np.corrcoef(pred_chr21.flatten(), target_chr21.flatten())[0][1]
    mean_corr = (corr + corr_chr21) / 2  # Calculating the average correlation
    tf_name.append(factors)
    corr_ls.append(mean_corr)
    print(factors, corr, corr_chr21, mean_corr)
succeed_h1 = pd.DataFrame({"tf":tf_name, "corr":corr_ls})

SUZ12 0.3712854370030025 0.23744112506265672 0.3043632810328296
POLR2A 0.48007490803256314 0.40052283060429716 0.44029886931843015
SRF 0.09189545754822558 0.0640031870280085 0.07794932228811705
CTCF 0.7482640118634031 0.7350285008573697 0.7416462563603864
H3K36me3 0.5875346276239615 0.5720453514035592 0.5797899895137604
H3K27ac 0.34924527868955496 0.24999911621221135 0.29962219745088314
H3K4me1 0.2621525429066594 0.32443727507907977 0.2932949089928696
MAFK 0.13769550824433271 0.11579143598492 0.12674347211462636
SIN3A 0.26516541499985424 0.19595079398764195 0.23055810449374808
CREB1 0.5826620819172966 0.524254513533563 0.5534582977254299
MAX 0.45299688770253127 0.42568376116254786 0.43934032443253956
SP1 0.1917036815075251 0.1237743162664277 0.1577389988869764
H3K4me3 0.3121826985297851 0.2170066199632835 0.2645946592465343
EP300 0.14111525626077143 0.10560682031442242 0.12336103828759692
HDAC2 0.5049583361733474 0.47179393031050254 0.48837613324192497
H2AFZ 0.30542742582908855 0.35055310332215733 0.32799026457562297
H3K9me3 0.16374562754081554 0.15063293829544394 0.15718928291812972
H3K9ac 0.6171642198549486 0.5397349606170502 0.5784495902359994
TAF1 0.477266399767445 0.3472941727747056 0.41228028627107527
JUND 0.3676759818371885 0.2712827677835209 0.3194793748103547
H3K27me3 0.3399315594312731 0.306559292859804 0.32324542614553853
RAD21 0.7495534600720177 0.7543571526981042 0.751955306385061
MYC -0.01437942572597649 -0.10520335972419687 -0.05979139272508668
GABPA 0.4392875544671953 0.5484238693396577 0.4938557119034265
CEBPB 0.17131363259167195 0.1280278382782017 0.1496707354349368
H3K4me2 0.5029347150901977 0.47012172528465973 0.4865282201874287
H4K20me1 0.43507881877048243 0.5395124546463369 0.4872956367084097
RFX5 0.1381613613876954 0.1354050781431041 0.13678321976539976
NRF1 0.44446642385206675 0.38470437163120097 0.41458539774163383
REST 0.09271565393506928 0.027834294488969714 0.060274974212019494
H3K79me2 0.46618595703615007 0.5434190394477298 0.5048024982419399
TCF12 0.18995388291061602 0.0681832302869928 0.1290685565988044

### A549

In [124]:
df_a549 = df[df["notes"].isin(["A549"])]
df_a549_select = df_a549[df_a549["factors"].isin(tf_list)]
df_a549_select = df_a549_select.drop_duplicates(subset=["factors"])

In [125]:
a549_pred = h5py.File("/home/suncz/work/s02/Encode_epigenome/results/benchmark/EPCOT/dataset/succeed/4-cells/model/csv/logs/version_0/A549.h5", "r")

In [126]:
prediction = a549_pred["prediction"]
prediction.shape

(19642, 896, 46)

In [128]:
tf_name = []
corr_ls = []
for i in df_a549_select.iloc:
    factors = i.factors
    name = i.name
    pred_index = tf_list_dict[factors]
    pred = prediction[:,:,pred_index]
    pred_chr10 = pred[contig_df[contig_df["chrom"] == "chr10"].index.values]
    target = np.load(f'/home/suncz/work/s02/Encode_epigenome/results/preprocessed/1m-akita/seqs_cov/{name}.h5.npy', allow_pickle=True)[:,64:-64]
    target_chr10 = target[contig_df[contig_df["chrom"] == "chr10"].index.values]
    corr = np.corrcoef(pred_chr10.flatten(), target_chr10.flatten())[0][1]
    pred_chr21 = pred[contig_df[contig_df["chrom"] == "chr21"].index.values]
    target_chr21 = target[contig_df[contig_df["chrom"] == "chr21"].index.values]
    corr_chr21 = np.corrcoef(pred_chr21.flatten(), target_chr21.flatten())[0][1]
    mean_corr = (corr + corr_chr21) / 2  # Calculating the average correlation
    tf_name.append(factors)
    corr_ls.append(mean_corr)
    print(factors, corr, corr_chr21, mean_corr)
succeed_a549 = pd.DataFrame({"tf":tf_name, "corr":corr_ls})
succeed_a549.to_csv('/home/suncz/work/s02/Encode_epigenome/results/benchmark/EPCOT/dataset/succeed/4-cells/model/csv/logs/version_0/a549_corr.csv', index=False)

EP300 0.627752229495903 0.6336107651594393 0.6306814973276711
RAD21 0.8319690374881319 0.8297436959450943 0.8308563667166131
H3K27ac 0.7892578460565655 0.7993969762184584 0.7943274111375119
MAZ 0.5215865188285017 0.5183092979586699 0.5199479083935858
MYC 0.24764416217477817 0.3266033689595923 0.2871237655671852
CTCF 0.8641751112298636 0.8879824285077496 0.8760787698688066
MAFK 0.23404755107510955 0.20306867762086145 0.2185581143479855
CEBPB 0.3881365211291003 0.37593735228780256 0.3820369367084514
RFX5 0.48694942085885046 0.44509259013912617 0.4660210054989883
SIN3A 0.6941071585992962 0.6724447907521637 0.68327597467573
RCOR1 0.36924616463240295 0.31939148451224153 0.3443188245723222
MAX 0.8311452004828235 0.807972169817621 0.8195586851502222
H3K9me3 0.38627584022614964 0.4835372893562447 0.43490656479119716
H3K4me1 0.7695925218794976 0.7712639242549977 0.7704282230672477
HDAC2 0.310626613927092 0.2846556398542318 0.2976411268906619
H3K4me2 0.8394574819312813 0.8602784356953642 0.8498679588133228
H3K4me3 0.8214959431380768 0.8309268301509966 0.8262113866445366
REST 0.20743678466939255 0.0767165815831548 0.14207668312627367
POLR2A 0.6020973355135796 0.6668658986080496 0.6344816170608145

In [8]:
df_hela = df[df["notes"].isin(["HeLa-S3"])]
# df_hela_select = df_hela[df_hela["factors"].isin(tf_list)]
# df_hela_select = df_hela_select.drop_duplicates(subset=["factors"])

In [9]:
df_hela["experiment"] == "ATAC-seq"

index
543     False
604     False
627     False
628     False
648     False
        ...
3053    False
3138    False
3348    False
3366    False
3462    False
Name: experiment, Length: 88, dtype: bool